"""Seed data for initial database population."""

from datetime import datetime, timedelta
from typing import List


def get_seed_jobs() -> List[dict]:
    """Get sample job data for seeding the database."""

    now = datetime.utcnow()

    return [
        {
            "title": "Software Developer",
            "company": "Mackay Digital Solutions",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$70,000 - $90,000 AUD",
            "description": "Join our growing team of developers working on cutting-edge web and mobile applications. You'll work on projects that make a real difference in the mining, agricultural, and tourism industries of Queensland.",
            "requirements": '["Bachelor\'s degree in Computer Science or related field", "3+ years of experience in Python, JavaScript, or Java", "Experience with web frameworks (Django, React, Spring)", "Knowledge of database systems (PostgreSQL, MySQL)", "Strong problem-solving skills", "Excellent communication skills"]',
            "benefits": '["Flexible working arrangements", "Professional development budget", "Health and wellness program", "Modern office in Mackay city center", "Close-knit team culture"]',
            "posted_date": now - timedelta(days=2),
            "expiry_date": now + timedelta(days=30),
            "industry": "Technology",
            "experience_level": "Mid",
            "remote_friendly": True,
        },
        {
            "title": "Mining Engineer",
            "company": "Queensland Mining Corp",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$95,000 - $120,000 AUD",
            "description": "We are seeking an experienced Mining Engineer to join our operations in the Bowen Basin. You'll be responsible for mine planning, operations optimization, and safety management.",
            "requirements": '["Bachelor\'s degree in Mining Engineering", "5+ years of mining operations experience", "Knowledge of mining software (Surpac, MineSched)", "Current First Aid Certificate", "Strong leadership and communication skills", "Current Queensland Mining Supervisor Certificate"]',
            "benefits": '["Excellent salary package", "Fly-in, fly-out arrangements available", "Comprehensive health insurance", "Annual bonus program", "Career advancement opportunities"]',
            "posted_date": now - timedelta(days=5),
            "expiry_date": now + timedelta(days=25),
            "industry": "Mining",
            "experience_level": "Senior",
            "remote_friendly": False,
        },
        {
            "title": "Registered Nurse - Emergency Department",
            "company": "Mackay Base Hospital",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$75,000 - $85,000 AUD",
            "description": "Join our Emergency Department team providing high-quality patient care. Work in a modern facility serving the greater Mackay region.",
            "requirements": '["Current AHPRA registration as Registered Nurse", "Minimum 2 years of emergency nursing experience", "Advanced life support certification", "Triage experience preferred", "Strong interpersonal skills", "Ability to work in high-pressure environments"]',
            "benefits": '["Salary packaging benefits", "Flexible shift arrangements", "Professional development opportunities", "Supportive team environment", "Public hospital benefits"]',
            "posted_date": now - timedelta(days=1),
            "expiry_date": now + timedelta(days=35),
            "industry": "Healthcare",
            "experience_level": "Mid",
            "remote_friendly": False,
        },
        {
            "title": "Marketing Coordinator",
            "company": "Tourism Mackay",
            "location": "Mackay, QLD",
            "job_type": "Part-time",
            "salary_range": "$50,000 - $60,000 AUD (pro-rata)",
            "description": "Help promote Mackay as a premier tourist destination. Coordinate marketing campaigns, manage social media, and organize tourism events.",
            "requirements": '["Bachelor\'s degree in Marketing or Communications", "2+ years of marketing experience", "Experience with social media management", "Graphic design skills (Adobe Creative Suite)", "Event management experience", "Passion for tourism and Mackay region"]',
            "benefits": '["Flexible working hours", "Travel opportunities within the region", "Professional development", "Creative and collaborative environment", "Work with tourism industry leaders"]',
            "posted_date": now - timedelta(days=3),
            "expiry_date": now + timedelta(days=27),
            "industry": "Tourism",
            "experience_level": "Entry",
            "remote_friendly": True,
        },
        {
            "title": "Agricultural Consultant",
            "company": "Queensland Agriculture Services",
            "location": "Mackay, QLD",
            "job_type": "Contract",
            "salary_range": "$80,000 - $100,000 AUD (annual equivalent)",
            "description": "Provide expert agricultural consulting services to sugarcane and cattle farmers in the Mackay region. Focus on sustainable farming practices and crop optimization.",
            "requirements": '["Bachelor\'s degree in Agriculture, Agronomy, or related field", "5+ years of agricultural consulting experience", "Knowledge of Queensland farming systems", "Experience with precision agriculture technologies", "Strong analytical and problem-solving skills", "Valid driver\'s license"]',
            "benefits": '["Flexible contract arrangements", "Travel allowance provided", "Professional independence", "Competitive rates", "Work with diverse farming operations"]',
            "posted_date": now - timedelta(days=7),
            "expiry_date": now + timedelta(days=23),
            "industry": "Agriculture",
            "experience_level": "Senior",
            "remote_friendly": False,
        },
        {
            "title": "Primary School Teacher",
            "company": "Mackay State School",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$70,000 - $95,000 AUD",
            "description": "Join our dedicated teaching team at Mackay State School. We are looking for passionate educators to inspire and educate our students from Prep to Year 6.",
            "requirements": '["Bachelor of Education or equivalent teaching qualification", "Current Queensland College of Teachers registration", "Demonstrated teaching experience with primary-aged children", "Strong classroom management skills", "Excellent communication and interpersonal skills", "Commitment to student welfare and development"]',
            "benefits": '["Government teacher salary and benefits", "Professional development opportunities", "Supportive school community", "Modern facilities and resources", "Work-life balance opportunities"]',
            "posted_date": now - timedelta(days=4),
            "expiry_date": now + timedelta(days=28),
            "industry": "Education",
            "experience_level": "Mid",
            "remote_friendly": False,
        },
        {
            "title": "Data Analyst",
            "company": "Mackay Regional Council",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$65,000 - $80,000 AUD",
            "description": "Analyze civic data to improve services for Mackay residents. Work on transportation, utilities, and community development projects using modern data analytics tools.",
            "requirements": '["Bachelor\'s degree in Data Science, Statistics, or related field", "2+ years of data analysis experience", "Proficiency in SQL, Python, or R", "Experience with data visualization tools (Tableau, Power BI)", "Strong analytical and problem-solving skills", "Ability to communicate findings to non-technical stakeholders"]',
            "benefits": '["Stable government employment", "Flexible working arrangements", "Professional development opportunities", "Comprehensive benefits package", "Work on meaningful civic projects"]',
            "posted_date": now - timedelta(days=6),
            "expiry_date": now + timedelta(days=24),
            "industry": "Government",
            "experience_level": "Entry",
            "remote_friendly": True,
        },
        {
            "title": "Chef de Partie",
            "company": "The Marina Restaurant",
            "location": "Mackay, QLD",
            "job_type": "Full-time",
            "salary_range": "$55,000 - $65,000 AUD",
            "description": "Lead a section in our award-winning restaurant specializing in fresh seafood and modern Australian cuisine. Join our passionate culinary team.",
            "requirements": '["Culinary qualification or equivalent experience", "3+ years of experience in a similar role", "Strong leadership and time management skills", "Knowledge of food safety and hygiene standards", "Ability to work under pressure", "Passion for culinary excellence"]',
            "benefits": '["Competitive salary plus tips", "Career advancement opportunities", "Modern commercial kitchen", "Staff meals provided", "Flexible shift patterns"]',
            "posted_date": now - timedelta(days=8),
            "expiry_date": now + timedelta(days=22),
            "industry": "Hospitality",
            "experience_level": "Mid",
            "remote_friendly": False,
        },
    ]
